feat: update module inputs for da solution
terraform-ibm-modules/terraform-ibm-scc-da pull request #53
Opened 2024-04-12 14:48 UTC by jor2

### Description

Update module inputs in da solution to attach workload protection instance.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Update module inputs in da solution to attach workload protection instance.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-04-12 14:52 UTC, jor2 commented
/run pipeline

2024-04-12 15:02 UTC, jor2 commented
/run pipeline

2024-04-14 19:25 UTC, ocofaigh requested changes
see comments

2024-04-14 19:25 UTC, ocofaigh commented on solutions/instances/variables.tf
> +variable "attach_wp_to_scc_instance" {
don't expose this - if `provision_scc_workload_protection` is true then the DA code should automatically set attach it to the SCC instance

2024-04-14 19:25 UTC, ocofaigh commented on tests/pr_test.go
> +		{Name: "attach_wp_to_scc_instance", Value: true, DataType: "bool"},
remove this since we will remove the `attach_wp_to_scc_instance` variable

2024-04-14 22:31 UTC, jor2 commented
/run pipeline

2024-04-14 22:42 UTC, jor2 commented
/run pipeline

2024-04-14 23:32 UTC, jor2 commented
https://github.com/terraform-ibm-modules/terraform-ibm-scc/pull/74

2024-04-15 08:49 UTC, ocofaigh commented on tests/pr_test.go
> +		{Name: "skip_scc_wp_auth_policy", Value: false, DataType: "bool"},
these are the default values so no need to explicitly specify here

2024-04-15 08:49 UTC, ocofaigh commented on solutions/instances/variables.tf
> +  description = "Set to true to skip the creation of an IAM authorization policy that permits the SCC instance created by this solution read access to the workload protection instance. Only used if `
remove `attach_wp_to_scc_instance` from the description - its no an exposed variable in this DA. I guess it should be replaced by `provision_scc_workload_protection`

2024-04-15 08:50 UTC, ocofaigh requested changes
see comments

2024-04-15 17:34 UTC, jor2 commented
/run pipeline

2024-04-16 09:02 UTC, ocofaigh approved these changes

2024-04-16 09:03 UTC, merged

2024-04-16 09:04 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/releases/tag/v1.4.0)
- `v1.4.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: